# Generated by Django 2.1 on 2019-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('action', 'Action'), ('fighting', 'Fighting'), ('strategy', 'Strategy'), ('horror', 'Horror'), ('intelligence', 'Intelligence'), ('straighten', 'Straighten'), ('old-games', 'Old Games'), ('adventures', 'Adventures'), ('racing-cars', 'Racing Cars'), ('reality-simulation', 'Reality Simulation'), ('sport', 'Sport'), ('light-entertaining', 'Light Entertaining'), ('fiction', 'fiction')], max_length=100)),
                ('description', models.CharField(max_length=30000)),
                ('cpu_l', models.CharField(max_length=200)),
                ('graphic_card_l', models.CharField(max_length=200)),
                ('ram_l', models.CharField(max_length=200)),
                ('cpu_h', models.CharField(max_length=200)),
                ('graphic_card_h', models.CharField(max_length=200)),
                ('ram_h', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('size_type', models.CharField(choices=[('MB', 'MB'), ('GB', 'GB')], default='MB', max_length=3)),
                ('download_num', models.IntegerField(default=0)),
                ('youtube_iframe', models.CharField(max_length=700)),
                ('download_link', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, default='default-profile-image.png', null=True, upload_to='media/game_image')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
