# Generated by Django 2.1 on 2019-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='default-profile-image.png', null=True, upload_to='game_image'),
        ),
    ]
